name: Build and deploy Node.js app to Azure Web App - RoseBudThorn

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read # Required for actions/checkout

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Ensures full repo is checked out

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install backend dependencies
              working-directory: express-backend
              run: npm install

            - name: Build backend (if applicable)
              working-directory: express-backend
              run: npm run build --if-present

            - name: Zip artifact for deployment
              working-directory: express-backend
              run: zip -r release.zip backend.js package.json node_modules .env # Adjust files as needed

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: express-backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write # Required for requesting JWT
            contents: read # Required for actions/checkout

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Install backend dependencies (after unzip)
              run: npm install

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F51166206B448BA9D9E7BAB5A0C38E9 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_860B0F8A9F2542A0AD66253774B5C856 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F1166AC7AD2B4A58B188F4E54CCE44E9 }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "RoseBudThorn"
                  slot-name: "Production"
                  package: .
